on:
  push:
    branches: [ "main", "AhmedBranch", "globuli94"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'sbt'
    - name: compile
      run: sbt compile
    - name: run tests
      run: sbt test


  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'sbt'
    - name: run tests
      run: sbt test
    - name: create report
      run: sbt clean coverage test coverageReport
    - name: upload
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: sbt coverageReport coveralls
